POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Semana OmniStack 4.0",
  "details": "Um evento para quem é apaixonado por tecnologia",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/889b68ac-4208-4466-91e7-f94fb06fef89/attendees
Content-Type: application/json

{
  "name":  "Erick Manuel Enrico Duarte",
  "email": "erickmanuelduarte@arcante.com.br"
}

###

GET http://localhost:3333/events/889b68ac-4208-4466-91e7-f94fb06fef89

###

GET http://localhost:3333/attendees/6/badge

###

GET http://localhost:3333/attendees/6/check-in

###

GET http://localhost:3333/events/bc231f7d-5a79-44f7-92e9-188d945e9882/attendees